version: '3'

services:
  db:
    image: mongo:4.2
    volumes:
      - db:/data/db/

  rita:
    image: quay.io/activecm/rita:${VERSION:-latest}
    build: .
    links:
      # give db an alias of "localhost" so that RITA's default config works unchanged
      - db:localhost
    volumes:
      - ${CONFIG:?You must provide a path to your CONFIG}:/etc/rita/config.yaml:ro
      - ${LOGS:?You must provide a path to your LOGS}:/logs:ro

volumes:
  db:
